baseURL = 'https://runxiyu.org/'
languageCode = 'en-us'
title = "Runxi Yu’s Website"

[permalinks]
blog = "/blog/:filename"

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
ordered = true
